[workspace]
channels = ["conda-forge"]
name = "GaltonBoard"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.11.9"
ipython = ">=9.4.0,<10"
scipy = ">=1.16.0,<2"
numpy = ">=2.3.2,<3"
pandas = ">=2.3.1,<3"
scikit-learn = ">=1.7.1,<2"
matplotlib = ">=3.10.3,<4"
seaborn = ">=0.13.2,<0.14"
tqdm = ">=4.67.1,<5"
hydra-core = ">=1.3.2,<2"
jupyter = ">=1.1.1,<2"

[pypi-dependencies]
pennylane = "==0.42.0"
pennylane-qiskit = ">=0.42.0, <0.43"
torch = { version = ">=2.4.1", index = "https://download.pytorch.org/whl/cu121" }
