defaults:
  - _self_
  - paths: paths
  - circuit: ideal
  - dataset: default
  - model: feed_forward_nn
  - loss_fn: cross_entropy
  - optimizer: adam
  - train: default

run_mode: train # Options are generate, train, test, and sample_dist
